### ISSUE TITLE
Chrome complaints about setting unsafe headers

### ISSUE THREAD

**Issue by davidcv5** [dart-lang/discoveryapis_commons#1]
Not sure if it's necessary or not, so I was looking around and found that
according to W3C, there is no need to set those headers.. 
http://www.w3.org/TR/XMLHttpRequest/#the-setrequestheader%28%29-method

Setting them results in Google Chrome throwing an error.
![screenshot 2015-04-18 13 13 30](https://cloud.githubusercontent.com/assets/1226611/7216422/7b7af34a-e5cd-11e4-85da-1ff0f7035063.png)

Here are the lines in question:
https://github.com/dart-lang/discoveryapis_commons/blob/master/lib/src/clients.dart#L201-L219

**Comment by sanmadjack** [comment]
As a workaround, you can create a custom BrowserClient implementation that removes these headers before calling send, like this:

    class CustomClient extends BrowserClient {
      CustomClient();
  
    @override
    Future<StreamedResponse> send(BaseRequest request) async {
      request.headers.remove(HttpHeaders.USER_AGENT);
      request.headers.remove(HttpHeaders.CONTENT_LENGTH);
      StreamedResponse response = await super.send(request);
      return response;
    }
    }

**Comment by tmst** [comment]
There's also the matter of removing the headers from the BrowserClient instance returned from flow.clientViaUserConsent(). Or perhaps there's a way to pass CustomClient into clientVia...(), but I woudn't know how that might be done.

**Comment by zreptil** [comment]
Four years later this is still an issue. I try to have an angulart webapp that uses google drive and i am looking in the code to not produce unwanted errors or warnings. But the user-agent and content-length headers errors are still there. Will there be a solution in the near future or has everybody to live with this errors when using the google apis?

**Comment by jonasfj** [comment]
See #30, which might just fix this...

Hmm, I've probably forgotten to merge and release said PR.

**Comment by jonasfj** [comment]
Fixed in `0.1.8+2`.
