### ISSUE TITLE
Dart 2 runtime failures in test

### ISSUE THREAD

**Issue by keertip** [dart-lang/discoveryapis_commons#18]
type '_ControllerStream<dynamic>' is not a subtype of type 'Stream<List<int>>' of 'stream' where
    _ControllerStream is from dart:async
    Stream is from dart:async
    List is from dart:core
    int is from dart:core
  
  package:_discoveryapis_commons/src/clients.dart                                                         Base64Encoder.bind
  dart:async                                                                                              Stream.transform
  ../..discoveryapis_commons/test/discoveryapis_commons_test.dart 137:14 

 type 'Future<dynamic>' is not a subtype of type 'FutureOr<StreamedResponse>' where
    Future is from dart:async
    FutureOr is from dart:async
    StreamedResponse is from package:http/src/streamed_response.dart
  
  ../../_discoveryapis_commons/test/discoveryapis_commons_test.dart 45:18   HttpServerMock.send.<fn>

  Expected: DetailedApiRequestError
    Actual: ?:<type '(Map<dynamic, dynamic>) => ApiRequestErrorDetail' is not a subtype of type '(dynamic) => dynamic' of 'f'>
  
  package:test                                                                                            expect
  ../../_discoveryapis_commons/test/discoveryapis_commons_test.dart 898:13  main.<fn>.<fn>.<fn>.<fn>.<fn>

**Comment by jakobr-google** [comment]
Fixed in #19.
