### ISSUE TITLE
Content-header length parse fails on null

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [dart-lang/discoveryapis_commons#28]
I wonder if 
`var contentLength = int.tryParse(response.headers['content-length']);`
can be replaced to 
```
var contentLength = response.headers['content-length'] != null
        ? int.tryParse(response.headers['content-length'])
        : null;
```

Sometimes that header is null but we can still use Media stream but request fails on tryParse since it on turn, fails on null.

**Comment by kevmoo** [comment]
CC @sortie

**Comment by BaurzhanSakhariev** [comment]
BTW, I believe it's related to https://github.com/dart-lang/discoveryapis_commons/issues/1 , so this null check can probably address both issues.

**Comment by sortie** [comment]
@kevmoo Did you mean @jonasfj? He is the current owner of the pub site.

**Comment by jonasfj** [comment]
This is was fixed in https://github.com/dart-lang/discoveryapis_commons/pull/24

**Comment by BaurzhanSakhariev** [comment]
Thanks a lot!
