### ISSUE TITLE
Source contains USES_DYNAMIC_AS_BOTTOM_ERRORS violations

### ISSUE THREAD

**Issue by srawlins** [dart-lang/discoveryapis_commons#9]
New Dart versions warn about using `dynamic` as "bottom" in the type system. More information here: https://github.com/dart-lang/sdk/issues/29630

All the violations are in `lib/src/clients.dart`. These are easy to fix; I'll send a PR.

**Comment by kevmoo** [comment]
CC @mkustermann @jakobr-google
